export function createEditorV2Runtime(input = {}) {
  const shell = {
    activeSectionName: input.activeSection?.name || "대형 없음",
    arrivalLabel: input.arrivalLabel,
    localSaveLabel: input.localSaveLabel,
    projectTitle: input.projectTitle,
    readonly: input.readonly,
    timeLabel: input.timeLabel
  };
  const stage = {
    activeSection: input.activeSection,
    activeTransitionPaths: input.activeTransitionPaths,
    dragPositions: input.dragPositions,
    focusedPerformerIds: input.focusedPerformerIds,
    frontZone: input.frontZone,
    performers: input.performers,
    stage3dProjection: input.stage3dProjection,
    stageDimensions: input.stageDimensions,
    stageReferences: input.stageReferences,
    stageSizeLabel: input.stageSizeLabel,
    stageViewMode: input.stageViewMode,
    transitionPathCount: input.transitionPathCount,
    visiblePositions: input.visiblePositions
  };
  const timeline = {
    currentSectionId: input.currentSectionId,
    hasUsableAudio: input.hasUsableAudio,
    isPlaying: input.isPlaying,
    playheadPixel: input.playheadPixel,
    snapPixel: input.snapPixel,
    sortedSections: input.sortedSections,
    timelineBlockedEdge: input.timelineBlockedEdge,
    timelineContentWidth: input.timelineContentWidth,
    timelineFormationBlocks: input.timelineFormationBlocks,
    timelineScrollX: input.timelineScrollX,
    timelineTicks: input.timelineTicks,
    timelineVisualSegments: input.timelineVisualSegments,
    timelineZoomLabel: input.timelineZoomLabel,
    waveformBars: input.waveformBars
  };
  const selection = {
    selectedPerformerId: input.selectedPerformerId,
    selectedPerformerIds: input.selectedPerformerIds,
    selectedSection: input.selectedSection,
    selectedSectionId: input.selectedSectionId,
    selectedStateText: input.selectedStateText,
    selectionVisualState: input.selectionVisualState
  };
  const inspector = {
    activeMobilePanelActionKey: input.activeMobilePanelActionKey,
    isMobilePanelOpen: input.isMobilePanelOpen,
    mobilePanelSize: input.mobilePanelSize,
    mobilePanelTitle: input.mobilePanelTitle
  };
  const actionModel = {
    globalActions: input.globalActions,
    mobileActions: input.mobileActions,
    topActionMenu: input.topActionMenu,
    topActionSurface: input.topActionSurface
  };
  const model = {
    actions: actionModel,
    inspector,
    selection,
    shell,
    stage,
    timeline,
    activeMobilePanelActionKey: input.activeMobilePanelActionKey,
    activeSection: input.activeSection,
    activeSectionName: shell.activeSectionName,
    activeTransitionPaths: input.activeTransitionPaths,
    arrivalLabel: input.arrivalLabel,
    currentSectionId: input.currentSectionId,
    dragPositions: input.dragPositions,
    focusedPerformerIds: input.focusedPerformerIds,
    frontZone: input.frontZone,
    globalActions: input.globalActions,
    hasUsableAudio: input.hasUsableAudio,
    isMobilePanelOpen: input.isMobilePanelOpen,
    isPlaying: input.isPlaying,
    localSaveLabel: input.localSaveLabel,
    mobileActions: input.mobileActions,
    mobilePanelSize: input.mobilePanelSize,
    mobilePanelTitle: input.mobilePanelTitle,
    performers: input.performers,
    playheadPixel: input.playheadPixel,
    projectTitle: input.projectTitle,
    readonly: input.readonly,
    redoDisabled: input.redoDisabled,
    selectedPerformerId: input.selectedPerformerId,
    selectedPerformerIds: input.selectedPerformerIds,
    selectedSection: input.selectedSection,
    selectedSectionId: input.selectedSectionId,
    selectedStateText: input.selectedStateText,
    selectionVisualState: input.selectionVisualState,
    snapPixel: input.snapPixel,
    sortedSections: input.sortedSections,
    stage3dProjection: input.stage3dProjection,
    stageDimensions: input.stageDimensions,
    stageReferences: input.stageReferences,
    stageSizeLabel: input.stageSizeLabel,
    stageViewMode: input.stageViewMode,
    timeLabel: input.timeLabel,
    timelineBlockedEdge: input.timelineBlockedEdge,
    timelineContentWidth: input.timelineContentWidth,
    timelineFormationBlocks: input.timelineFormationBlocks,
    timelineScrollX: input.timelineScrollX,
    timelineTicks: input.timelineTicks,
    timelineVisualSegments: input.timelineVisualSegments,
    timelineZoomLabel: input.timelineZoomLabel,
    topActionMenu: input.topActionMenu,
    topActionSurface: input.topActionSurface,
    transitionPathCount: input.transitionPathCount,
    undoDisabled: input.undoDisabled,
    visiblePositions: input.visiblePositions,
    waveformBars: input.waveformBars
  };

  const actions = {
    addSection: input.addSection,
    clearDrag: input.clearDrag,
    clearTimelineSelection: input.clearTimelineSelection,
    closeMobilePanel: input.closeMobilePanel,
    closeTopActionMenu: input.closeTopActionMenu,
    cycleMobilePanelSize: input.cycleMobilePanelSize,
    finishActiveDrag: input.finishActiveDrag,
    handleMobileAction: input.handleMobileAction,
    handleStageTap: input.handleStageTap,
    onFormationPointerDown: input.onFormationPointerDown,
    onFormationSelect: input.onFormationSelect,
    onStagePointerDown: input.onStagePointerDown,
    onStagePointerMove: input.onStagePointerMove,
    onTimelinePointerDown: input.onTimelinePointerDown,
    onTimelinePointerMove: input.onTimelinePointerMove,
    onTimelinePointerUp: input.onTimelinePointerUp,
    onTimelineWheel: input.onTimelineWheel,
    openAudioFilePicker: input.openAudioFilePicker,
    openTopActionMenu: input.openTopActionMenu,
    redoPlan: input.redoPlan,
    renderDownloadMenu: input.renderDownloadMenu,
    renderMobilePanelContent: input.renderMobilePanelContent,
    renderMoreMenu: input.renderMoreMenu,
    renderShareMenu: input.renderShareMenu,
    selectPerformer: input.selectPerformer,
    setStageViewMode: input.setStageViewMode,
    svgRef: input.svgRef,
    timelineViewportRef: input.timelineViewportRef,
    togglePlayback: input.togglePlayback,
    toggleStageReferences: input.toggleStageReferences,
    undoPlan: input.undoPlan,
    zoomTimelineBy: input.zoomTimelineBy
  };

  return { actions, model };
}
